// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH1SxpyZFkXG-GNmVaBCsXlf3KU9PQVvw',
    appId: '1:1067176453727:web:66281960df175a653e1dea',
    messagingSenderId: '1067176453727',
    projectId: 'safecityproject-28555',
    authDomain: 'safecityproject-28555.firebaseapp.com',
    storageBucket: 'safecityproject-28555.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJy4YldlDUDqGMoWtc617QKH9KuSUXcKg',
    appId: '1:1067176453727:android:be407e99689cbad93e1dea',
    messagingSenderId: '1067176453727',
    projectId: 'safecityproject-28555',
    storageBucket: 'safecityproject-28555.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB45rfY_Vor4BT8_IFZf5uzZrWG5Y96sog',
    appId: '1:1067176453727:ios:5114d7f5db6de1173e1dea',
    messagingSenderId: '1067176453727',
    projectId: 'safecityproject-28555',
    storageBucket: 'safecityproject-28555.appspot.com',
    iosClientId: '1067176453727-o4gpmg7vsv39mh2r8imjuevpevdggh0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeCityProject',
  );
}
