// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfpPCegrfHoo1ZVY801z95C3ayX3W0JmQ',
    appId: '1:750786991319:web:1b726ea7795f67a6d48c92',
    messagingSenderId: '750786991319',
    projectId: 'chatboxsafecity',
    authDomain: 'chatboxsafecity.firebaseapp.com',
    storageBucket: 'chatboxsafecity.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG8UeHjIVRBLiCcv3v0V9Bgdd9SLsnOsw',
    appId: '1:750786991319:android:a9dd5fec1a7c9bf0d48c92',
    messagingSenderId: '750786991319',
    projectId: 'chatboxsafecity',
    storageBucket: 'chatboxsafecity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKxNIxZs6CTU1qaK-6Xj0B0y7p4Gflie4',
    appId: '1:750786991319:ios:195a96ed4f220fc6d48c92',
    messagingSenderId: '750786991319',
    projectId: 'chatboxsafecity',
    storageBucket: 'chatboxsafecity.appspot.com',
    iosClientId: '750786991319-4uvicg18mk4bqpjfmbk795lju17jktqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeCityProject',
  );
}
